# Generated by Django 5.2.16 on 2026-07-20 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('geo', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(blank=True, default='axa', help_text="Scraper plugin anahtarı. Boş bırakılırsa 'axa' varsayılır.", max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('RUNNING', 'Çalışıyor'), ('SUCCESS', 'Başarılı'), ('PARTIAL', 'Kısmi Başarılı'), ('FAILED', 'Başarısız')], default='PENDING', max_length=20)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('log_file_path', models.CharField(blank=True, max_length=500, verbose_name='Log Dosyası')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm şirketler için çalışır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scrape_jobs', to='companies.insurancecompany')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scrape_jobs', to='geo.district')),
                ('institution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scrape_jobs', to='products.institutiontype')),
                ('product_type', models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm ürün tipleri için çalışır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scrape_jobs', to='products.producttype')),
                ('province', models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm iller için çalışır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scrape_jobs', to='geo.province')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scrape İşi',
                'verbose_name_plural': 'Scrape İşleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
