# Generated by Django 5.2.16 on 2026-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='source_key',
            field=models.CharField(blank=True, choices=[('axa', 'AXA'), ('allianz', 'Allianz'), ('anadolu', 'Anadolu')], default='axa', help_text="Scraper plugin anahtarı. Boş bırakılırsa 'axa' varsayılır.", max_length=50),
        ),
    ]
