# Generated by Django 5.2.16 on 2026-07-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='source_key',
            field=models.CharField(blank=True, default='tss_portal', help_text="Scraper plugin anahtarı. Boş bırakılırsa 'tss_portal' varsayılır.", max_length=50),
        ),
    ]
