# Generated by Django 5.2.16 on 2026-07-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_scrapejob_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='pid',
            field=models.PositiveIntegerField(blank=True, help_text="Job'u çalıştıran worker process'in PID'i (log stream panelinde gösterilir).", null=True),
        ),
    ]
