# Generated by Django 5.2.16 on 2026-07-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_restructure_multi_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='source_key',
            field=models.CharField(blank=True, default='axa', help_text="Scraper plugin anahtarı. Boş bırakılırsa 'axa' varsayılır.", max_length=50),
        ),
    ]
