# Generated by Django 5.2.16 on 2026-07-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_scrapejob_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='log_file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Log Dosyası'),
        ),
    ]
