# Generated by Django 5.2.16 on 2026-07-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sigorta Şirketi',
                'verbose_name_plural': 'Sigorta Şirketleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('shown_by_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='companies.insurancecompany')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='products.producttype')),
            ],
            options={
                'verbose_name': 'Network / Plan Grubu',
                'verbose_name_plural': "Network'ler / Plan Grupları",
                'ordering': ['company', 'product_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="İnsan-okunabilir isim. Örn: 'Sağlığım Tamam Sigortası', 'CHECK UP'", max_length=150)),
                ('code', models.CharField(help_text="İç kod. Örn: 'AXA_TSS_17'. Otomatik üretilir veya manuel girilebilir.", max_length=80)),
                ('external_service_id', models.CharField(help_text="Şirket API'sindeki servis/filtre ID'si. Örn AXA için '17'.", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_applications', to='companies.insurancecompany')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_applications', to='companies.network')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_applications', to='products.producttype')),
            ],
            options={
                'verbose_name': 'Poliçe Uygulaması',
                'verbose_name_plural': 'Poliçe Uygulamaları',
                'ordering': ['company', 'product_type', 'network', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('company', 'product_type', 'external_id'), name='unique_network_per_company_product'),
        ),
        migrations.AddConstraint(
            model_name='policyapplication',
            constraint=models.UniqueConstraint(fields=('company', 'product_type', 'external_service_id'), name='unique_policy_app_per_company_product_service'),
        ),
    ]
