# Generated by Django 5.2.16 on 2026-07-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('shown_by_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='companies.insurancecompany')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='products.producttype')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': "Network'ler",
                'ordering': ['company', 'product_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'product_type', 'external_id'), name='unique_network_per_company_product')],
            },
        ),
    ]
