# Generated by Django 5.2.16 on 2026-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
