# Generated by Django 5.2.16 on 2026-07-20 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_network'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="İnsan-okunabilir isim. Örn: 'Sağlığım Tamam Sigortası', 'CHECK UP'", max_length=150)),
                ('code', models.CharField(help_text="İç kod. Örn: 'AXA_TSS_17'. Otomatik üretilir veya manuel girilebilir.", max_length=80)),
                ('external_service_id', models.CharField(help_text="Şirket API'sindeki servis/filtre ID'si. Örn AXA için '17'.", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poliçe Uygulaması',
                'verbose_name_plural': 'Poliçe Uygulamaları',
                'ordering': ['company', 'product_type', 'network', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['company', 'product_type', 'name'], 'verbose_name': 'Network / Plan Grubu', 'verbose_name_plural': "Network'ler / Plan Grupları"},
        ),
        migrations.RemoveConstraint(
            model_name='network',
            name='unique_network_per_company_product',
        ),
        migrations.AlterField(
            model_name='network',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('company', 'product_type', 'external_id'), name='unique_network_per_company_product'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_applications', to='companies.insurancecompany'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_applications', to='companies.network'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_applications', to='products.producttype'),
        ),
        migrations.AddConstraint(
            model_name='policyapplication',
            constraint=models.UniqueConstraint(fields=('company', 'product_type', 'external_service_id'), name='unique_policy_app_per_company_product_service'),
        ),
    ]
