# Generated by Django 5.2.16 on 2026-07-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_restructure_multi_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancecompany',
            name='external_id',
        ),
    ]
