# Generated by Django 5.2.16 on 2026-07-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('plate_code', models.CharField(blank=True, help_text="Plaka kodu, orn: '34'", max_length=2, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'db_table': 'provinces',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='provinces_is_acti_d6b5a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('province', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='geo.province')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'db_table': 'districts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['province', 'is_active'], name='districts_provinc_4819fa_idx'), models.Index(fields=['is_active', 'name'], name='districts_is_acti_391473_idx')],
                'constraints': [models.UniqueConstraint(fields=('province', 'name'), name='unique_district_per_province')],
            },
        ),
    ]
