# Generated by Django 5.2.16 on 2026-07-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('geo', '0001_initial'),
        ('products', '0001_initial'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='geo.district')),
                ('institution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='products.institutiontype')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='geo.province')),
            ],
            options={
                'verbose_name': 'Sağlık Kurumu',
                'verbose_name_plural': 'Sağlık Kurumları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('coverage_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.insurancecompany')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='institutions.healthinstitution')),
                ('last_scrape_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scraper.scrapejob')),
                ('networks', models.ManyToManyField(blank=True, related_name='contracts', to='companies.network')),
                ('policy_applications', models.ManyToManyField(blank=True, related_name='contracts', to='companies.policyapplication')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='products.producttype')),
            ],
            options={
                'verbose_name': 'Kurum Anlaşması',
                'verbose_name_plural': 'Kurum Anlaşmaları',
                'ordering': ['company', 'product_type', 'institution'],
            },
        ),
        migrations.AddIndex(
            model_name='healthinstitution',
            index=models.Index(fields=['province', 'district'], name='institution_provinc_b8d23f_idx'),
        ),
        migrations.AddIndex(
            model_name='healthinstitution',
            index=models.Index(fields=['institution_type'], name='institution_institu_531b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='healthinstitution',
            index=models.Index(fields=['slug'], name='institution_slug_b27cda_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncontract',
            index=models.Index(fields=['company', 'product_type', 'is_active'], name='institution_company_08ed3c_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncontract',
            index=models.Index(fields=['institution', 'company'], name='institution_institu_0f4ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncontract',
            index=models.Index(fields=['is_active', 'last_seen_at'], name='institution_is_acti_25a41e_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutioncontract',
            constraint=models.UniqueConstraint(fields=('company', 'product_type', 'external_id'), name='unique_contract_per_company_product_external'),
        ),
    ]
