# Generated by Django 5.2.16 on 2026-07-13 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('geo', '0001_initial'),
        ('products', '0001_initial'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='geo.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='companies.insurancecompany')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='geo.district')),
                ('institution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='products.institutiontype')),
                ('last_scrape_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scraper.scrapejob')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='products.producttype')),
            ],
            options={
                'verbose_name': 'Sağlık Kurumu',
                'verbose_name_plural': 'Sağlık Kurumları',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'city', 'product_type'], name='institution_company_f8a5f5_idx'), models.Index(fields=['city', 'district'], name='institution_city_id_789dcd_idx'), models.Index(fields=['institution_type'], name='institution_institu_531b9b_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'product_type', 'external_id'), name='unique_institution_per_company_product')],
            },
        ),
    ]
