# Generated by Django 5.2.16 on 2026-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_network'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinstitution',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='companies.network'),
        ),
    ]
