from django.db import migrations


class Migration(migrations.Migration):
    """0001_initial daha önce silinip yeniden oluşturulan migration dosyaları yüzünden
    django_migrations'ta 'applied' görünüyordu ama InstitutionContract.policy_applications
    ve InstitutionContract.networks M2M ara tabloları DB'de hiç yaratılmamıştı.

    Model state zaten 0001_initial'de doğru tanımlı olduğu için burada sadece
    eksik tabloları DB'ye ekliyoruz, migration state'i değiştirmiyoruz.
    """

    dependencies = [
        ("institutions", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        (
                            'CREATE TABLE IF NOT EXISTS "institutions_institutioncontract_networks" '
                            '("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, '
                            '"institutioncontract_id" bigint NOT NULL, "network_id" bigint NOT NULL)'
                        ),
                        (
                            'ALTER TABLE "institutions_institutioncontract_networks" '
                            'ADD CONSTRAINT "institutions_institution_institutioncontract_id_n_d01ef83a_uniq" '
                            'UNIQUE ("institutioncontract_id", "network_id")'
                        ),
                        (
                            'ALTER TABLE "institutions_institutioncontract_networks" '
                            'ADD CONSTRAINT "institutions_institu_institutioncontract__6de15754_fk_instituti" '
                            'FOREIGN KEY ("institutioncontract_id") REFERENCES "institutions_institutioncontract" ("id") '
                            'DEFERRABLE INITIALLY DEFERRED'
                        ),
                        (
                            'ALTER TABLE "institutions_institutioncontract_networks" '
                            'ADD CONSTRAINT "institutions_institu_network_id_6cd3252b_fk_companies" '
                            'FOREIGN KEY ("network_id") REFERENCES "companies_network" ("id") '
                            'DEFERRABLE INITIALLY DEFERRED'
                        ),
                        (
                            'CREATE INDEX "institutions_institutionco_institutioncontract_id_6de15754" '
                            'ON "institutions_institutioncontract_networks" ("institutioncontract_id")'
                        ),
                        (
                            'CREATE INDEX "institutions_institutioncontract_networks_network_id_6cd3252b" '
                            'ON "institutions_institutioncontract_networks" ("network_id")'
                        ),
                        (
                            'CREATE TABLE IF NOT EXISTS "institutions_institutioncontract_policy_applications" '
                            '("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, '
                            '"institutioncontract_id" bigint NOT NULL, "policyapplication_id" bigint NOT NULL)'
                        ),
                        (
                            'ALTER TABLE "institutions_institutioncontract_policy_applications" '
                            'ADD CONSTRAINT "institutions_institution_institutioncontract_id_p_1e817e69_uniq" '
                            'UNIQUE ("institutioncontract_id", "policyapplication_id")'
                        ),
                        (
                            'ALTER TABLE "institutions_institutioncontract_policy_applications" '
                            'ADD CONSTRAINT "institutions_institu_institutioncontract__92d6512b_fk_instituti" '
                            'FOREIGN KEY ("institutioncontract_id") REFERENCES "institutions_institutioncontract" ("id") '
                            'DEFERRABLE INITIALLY DEFERRED'
                        ),
                        (
                            'ALTER TABLE "institutions_institutioncontract_policy_applications" '
                            'ADD CONSTRAINT "institutions_institu_policyapplication_id_a09afc0f_fk_companies" '
                            'FOREIGN KEY ("policyapplication_id") REFERENCES "companies_policyapplication" ("id") '
                            'DEFERRABLE INITIALLY DEFERRED'
                        ),
                        (
                            'CREATE INDEX "institutions_institutionco_institutioncontract_id_92d6512b" '
                            'ON "institutions_institutioncontract_policy_applications" ("institutioncontract_id")'
                        ),
                        (
                            'CREATE INDEX "institutions_institutionco_policyapplication_id_a09afc0f" '
                            'ON "institutions_institutioncontract_policy_applications" ("policyapplication_id")'
                        ),
                    ],
                    reverse_sql=[
                        'DROP TABLE IF EXISTS "institutions_institutioncontract_networks"',
                        'DROP TABLE IF EXISTS "institutions_institutioncontract_policy_applications"',
                    ],
                ),
            ],
        ),
    ]
