# Generated by Django 5.2.16 on 2026-07-20 09:34
# Hand-edited to include data migration:
#   Mevcut HealthInstitution (company/product_type/external_id/networks/last_seen_at/last_scrape_job
#   bilgileri) yeni InstitutionContract tablosuna kopyalanır, ardından eski alanlar drop edilir.

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def forward_create_contracts(apps, schema_editor):
    """
    Mevcut HealthInstitution kayıtlarından InstitutionContract oluştur.

    Dikkat: Bu noktada HealthInstitution'da hâlâ company/product_type/external_id/networks alanları
    mevcut (henüz drop edilmedi). InstitutionContract tablosu oluşturuldu ama alanları henüz bağlı değil
    — bu yüzden raw SQL veya ORM historical model kullanıyoruz.

    Ayrıca slug unique constraint henüz aktif değil; slug çakışmalarını burada çözeceğiz.
    """
    HealthInstitution = apps.get_model("institutions", "HealthInstitution")
    InstitutionContract = apps.get_model("institutions", "InstitutionContract")

    # slug unique yapılacak — önce çakışmaları düzeltelim
    # Aynı slug'a sahip birden fazla kayıt varsa (company farklı ama kurum aynı):
    # hepsini tek slug altında birleştir, diğerlerini sil (contract'a taşındıktan sonra).

    seen_slugs = {}
    to_merge = {}  # slug -> (canonical_institution, [duplicate_institutions])

    for inst in HealthInstitution.objects.select_related("city", "district").order_by("id"):
        city_name = inst.city.name if inst.city_id else ""
        district_name = inst.district.name if inst.district_id else ""
        base_slug = slugify(f"{inst.name}-{city_name}", allow_unicode=False)[:300]
        if not base_slug:
            base_slug = slugify(inst.name, allow_unicode=False)[:300] or f"institution-{inst.pk}"

        if base_slug not in seen_slugs:
            seen_slugs[base_slug] = inst.pk
            inst.slug = base_slug
            inst.save(update_fields=["slug"])
        else:
            # Çakışma — district ile genişlet
            extended = slugify(f"{inst.name}-{city_name}-{district_name}", allow_unicode=False)[:300]
            if extended and extended not in seen_slugs:
                seen_slugs[extended] = inst.pk
                inst.slug = extended
                inst.save(update_fields=["slug"])
            else:
                # Hâlâ çakışma — pk suffix ekle
                unique = f"{base_slug}-{inst.pk}"[:300]
                seen_slugs[unique] = inst.pk
                inst.slug = unique
                inst.save(update_fields=["slug"])

    # Her HealthInstitution için InstitutionContract oluştur
    for inst in HealthInstitution.objects.select_related("company", "product_type").all():
        if not inst.company_id or not inst.product_type_id:
            continue  # eksik FK → atla

        contract, created = InstitutionContract.objects.get_or_create(
            institution=inst,
            company=inst.company,
            product_type=inst.product_type,
            defaults={
                "external_id": str(inst.external_id) if inst.external_id else f"legacy-{inst.pk}",
                "coverage_notes": "",
                "is_active": inst.is_active,
                "last_seen_at": inst.last_seen_at,
                "last_scrape_job": inst.last_scrape_job,
                "raw_payload": inst.raw_payload,
            },
        )

        # Networks M2M kopyala
        if created:
            for network in inst.networks.all():
                contract.networks.add(network)


def reverse_create_contracts(apps, schema_editor):
    """Geri alma: InstitutionContract tablosunu temizle."""
    InstitutionContract = apps.get_model("institutions", "InstitutionContract")
    InstitutionContract.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_restructure_multi_source'),
        ('geo', '0001_initial'),
        ('institutions', '0002_healthinstitution_networks'),
        ('products', '0001_initial'),
        ('scraper', '0002_restructure_multi_source'),
    ]

    operations = [
        # 1. Yeni InstitutionContract tablosunu oluştur (henüz FK'lar yok)
        migrations.CreateModel(
            name='InstitutionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('coverage_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kurum Anlaşması',
                'verbose_name_plural': 'Kurum Anlaşmaları',
                'ordering': ['company', 'product_type', 'institution'],
            },
        ),
        # 2. FK'ları ekle (data migration'dan önce gerekli)
        migrations.AddField(
            model_name='institutioncontract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.insurancecompany'),
        ),
        migrations.AddField(
            model_name='institutioncontract',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='institutions.healthinstitution'),
        ),
        migrations.AddField(
            model_name='institutioncontract',
            name='last_scrape_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scraper.scrapejob'),
        ),
        migrations.AddField(
            model_name='institutioncontract',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='companies.network'),
        ),
        migrations.AddField(
            model_name='institutioncontract',
            name='policy_applications',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='companies.policyapplication'),
        ),
        migrations.AddField(
            model_name='institutioncontract',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='products.producttype'),
        ),
        # 3. DATA MIGRATION: mevcut HealthInstitution → InstitutionContract
        migrations.RunPython(forward_create_contracts, reverse_create_contracts),
        # 4. Artık eski alanları HealthInstitution'dan kaldır (IF EXISTS ile hem local hem canlı DB uyumlu)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE institutions_healthinstitution DROP CONSTRAINT IF EXISTS unique_institution_per_company_product;
                    ALTER TABLE institutions_healthinstitution DROP CONSTRAINT IF EXISTS unique_institution_per_company_product_source;
                    DROP INDEX IF EXISTS institution_company_f8a5f5_idx;
                    DROP INDEX IF EXISTS institution_source_17aaef_idx;
                    ALTER TABLE institutions_healthinstitution DROP COLUMN IF EXISTS source;
                    """
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='healthinstitution',
                    name='unique_institution_per_company_product',
                ),
                migrations.RemoveIndex(
                    model_name='healthinstitution',
                    name='institution_company_f8a5f5_idx',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='healthinstitution',
            name='company',
        ),
        migrations.RemoveField(
            model_name='healthinstitution',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='healthinstitution',
            name='last_scrape_job',
        ),
        migrations.RemoveField(
            model_name='healthinstitution',
            name='last_seen_at',
        ),
        migrations.RemoveField(
            model_name='healthinstitution',
            name='networks',
        ),
        migrations.RemoveField(
            model_name='healthinstitution',
            name='product_type',
        ),
        # 5. Kalan alan değişiklikleri
        migrations.AlterField(
            model_name='healthinstitution',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='healthinstitution',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='healthinstitution',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthinstitution',
            name='slug',
            field=models.SlugField(max_length=320, unique=True),
        ),
        # 6. Index ve constraint'ler
        migrations.AddIndex(
            model_name='healthinstitution',
            index=models.Index(fields=['slug'], name='institution_slug_b27cda_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncontract',
            index=models.Index(fields=['company', 'product_type', 'is_active'], name='institution_company_08ed3c_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncontract',
            index=models.Index(fields=['institution', 'company'], name='institution_institu_0f4ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncontract',
            index=models.Index(fields=['is_active', 'last_seen_at'], name='institution_is_acti_25a41e_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutioncontract',
            constraint=models.UniqueConstraint(
                fields=('company', 'product_type', 'external_id'),
                name='unique_contract_per_company_product_external',
            ),
        ),
    ]
